### ISSUE TITLE
Periodically get `Exception in callback of async function: TypeError: Object.keys called on non-object` errors in Meteor console

### ISSUE THREAD

**Issue by sunny-g** [VeliovGroup/ostrio-Neo4jreactivity#48] opened 2015-06-24 05:11 UTC
This error is periodically occurs when running my Meteor app, but not when explicitly running any queries. Any ideas of where it's coming from?
```
Exception in callback of async function: TypeError: Object.keys called on non-object
at Function.keys (native)
at Function._.each._.forEach (packages/underscore/underscore.js:111:1)
at packages/ostrio:neo4jreactivity/neo4jreactivity_driver.coffee:787:11
at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
at Object.Meteor.neo4j.parseSensitivities (packages/ostrio:neo4jreactivity/neo4jreactivity_driver.coffee:786:9)
at Object.Meteor.neo4j.cache.put (packages/ostrio:neo4jreactivity/neo4jreactivity_driver.coffee:595:37)
at packages/ostrio:neo4jreactivity/neo4jreactivity_driver.coffee:7:12
at runWithEnvironment (packages/meteor/dynamics_nodejs.js:108:1)
at packages/ostrio:neo4jreactivity/neo4jreactivity_driver.coffee:683:37
```

**Comment by dr-dimitru** [comment] 2015-06-24 11:50
@sunny-g could you provide any use case, user story or/and link to code where Neo4j driver is used
Also, is this error stops or cause server restarts?

I guess underscore's `_.each()` somehow receives non-object as a first argument. Need to find out how this may happen.

**Comment by dr-dimitru** [comment] 2015-06-25 17:02
@sunny-g Any news on your end?

**Comment by sunny-g** [comment] 2015-06-26 17:23
Hey @dr-dimitru, sorry for the delay. I pretty much only use neo4j in two ways right now, which you can see in this file: https://github.com/sunny-g/whuffie/blob/master/server/db/neoOperations.js

Essentially, when my server gets message from another network, it calls the appropriate neo4j operation and then wraps its callback in a Fiber; the callback right now is always a Mongo operation to save some of the same data in a traditional Meteor Collection. And again, these errors don't occur when I run a query. 

Also, the server doesn't error out or restart when this occurs, but it happens randomly and often enough after upgrading to the latest version of neo4j-reactivity that I just wanted to bring it to your attention and see if you have any tips on how I might debug something like this since the stack trace is so unhelpful.

**Comment by dr-dimitru** [comment] 2015-06-26 17:38
Do not use `Fibers`, use:
```coffeescript
bound = Meteor.bindEnvironment (callback) ->
    return callback()

#then in async callback:
obj.forEach (user) ->
     bound ->
          return 'something here'
 ```
 or at least `new Future()`

Move from `fiber` to `Meteor.bindEnvironment ` then let me know how it's going, ok?

**Comment by sunny-g** [comment] 2015-06-27 22:00
Hey @dr-dimitru, I don't want to derail the original intention of this post so I created an [issue](https://github.com/sunny-g/whuffie/issues/14) on my repo detailing why I'm forced to use the ```Fiber``` in hopes of detailing what I'm misunderstanding/misarchitecting about my code. Any help or guidance you could provide would be very very appreciated. Thanks!

**Comment by dr-dimitru** [comment] 2015-07-07 11:14
@sunny-g original issue with wrong argument on `_.each()` should be fixed at [v0.8.4](https://github.com/VeliovGroup/ostrio-Neo4jreactivity/releases/tag/v0.8.4)
Could you please check on your end?

**Comment by sunny-g** [comment] 2015-07-13 04:31
@dr-dimitru Hey, I just wanted to check in and thank you so much for fixing this issue so promptly and commenting on the other. I haven't had the time to check the fixes out, but I'll get back to you the minute I do. Thanks again for being so on top of these!

**Comment by dr-dimitru** [comment] 2015-08-24 13:39
Closed nude to no response. And this issue isn't reproduced on our end.

**Comment by dr-dimitru** [comment] 2015-08-24 13:40
Closed due to no response. And this issue isn't reproduced on our end.

**Closed by dr-dimitru** 2015-08-24 13:40 UTC
