### ISSUE TITLE
neo4j database getting written to but not updating neo4jCache

### ISSUE THREAD

**Issue by alexfrieden** [VeliovGroup/ostrio-Neo4jreactivity#30] opened 2015-04-11 22:25 UTC
So we are seeing neo4j getting written to.  However the `neo4jCache` is not updating.  When I do ctrl + M to see the debugger and go to neo4jCache it is showing neo4jCache initially it says 1/1 in the right hand corner.  However when I move the elements around to update neo4j, I start to see 1/2, 1/3, 1/4, etc.  Where the final one is the correct one.  How do I force meteor to reactively use the final one in the chain of updates?  Am I doing something wrong here?  Please let me know what I can provide to help debug easier.  

This code is https://github.com/parallelsio/core-modules under the neo4j branch

**Comment by lifeinchords** [comment] 2015-04-11 22:58
Just a quick note - Control + M is not native to Meteor platform.
It's a shortcut enabled by the https://github.com/msavin/Mongol and the same author's Jetsetter package

**Comment by dr-dimitru** [comment] 2015-04-12 01:00
Hi @alexfrieden , @lifeinchords ,

You should try to add some unique IDs to nodes, for example via `Random.id([n])`
And use in both write and read queries.

BTW `neo4jCache` not suppose to hold all neo4j data, it hold only data you're wrote or requested from server

Could you give a code (or query) examples, when you CREATE or UPDATE nodes in Neo4j but it's not updated reactively

**Comment by alexfrieden** [comment] 2015-04-12 01:03
Absolutely.  Query in our publications.js is:
```
'updateBitPosition': function(){
		// console.log("position_x");
		// return 'MATCH n WHERE id(n)={_id} SET n.position_x = { position_x } RETURN';
		var cypherQuery = 'MATCH n WHERE id(n)={_id} SET n.position_x = { position_x } RETURN n';
		console.log(cypherQuery)
		return cypherQuery;
	}
```

**Comment by dr-dimitru** [comment] 2015-04-12 01:12
@alexfrieden can't find what and where you are updating or creating in neo4j

**Comment by dr-dimitru** [comment] 2015-04-12 01:14
@alexfrieden where do you retrieve this data?

**Comment by alexfrieden** [comment] 2015-04-12 02:15
Whole publications.js:
```
Meteor.neo4j.methods({
	'allBits': function(){
	  return 'MATCH a RETURN a';
	},
	'updateBitPosition': function(){
		// console.log("position_x");
		// return 'MATCH n WHERE id(n)={_id} SET n.position_x = { position_x } RETURN';
		var cypherQuery = 'MATCH n WHERE id(n)={_id} SET n.position_x = { position_x } RETURN n';
		console.log(cypherQuery)
		return cypherQuery;
	}
});
```

Then in our population methods we grab all the pieces.  This populates one of our pages:
```Template.map.helpers({
  bits: function() {
    var myBits = Template.instance().bits.get();
    console.log("returned bits below")
    console.log(myBits);

    return myBits;
  }
});

 Template.map.created = function(){
  var self = this;
  console.log('map rendered.');
  self.bits = new ReactiveVar(false);
  Meteor.neo4j.call('allBits',{},function(error,data) {
      console.log(data['a']);
      self.bits.set(data['a']);
  });
};
```

**Comment by dr-dimitru** [comment] 2015-04-12 03:09
@alexfrieden try to change this:
```javascript
var cypherQuery = 'MATCH n WHERE id(n)={_id} SET n.position_x = { position_x } RETURN n';
```
into this:
```javascript
var cypherQuery = 'MATCH n WHERE id(a)={_id} SET a.position_x = { position_x } RETURN a';
```

Why: cause above this code you have subscribed on `a` nodes without any attributes:
```javascript
return 'MATCH a RETURN a';
```

**Comment by alexfrieden** [comment] 2015-04-12 03:31
Hmmm, tried that it appears that the client is still not updating the data on its end.

**Comment by dr-dimitru** [comment] 2015-04-12 19:11
@alexfrieden
I see on penultimate line `MATCH a RETURN a`, but you're updating `n`(s), change to `MATCH n RETURN n` or use `:Bit` label, read more [here](https://github.com/VeliovGroup/ostrio-Neo4jreactivity#about-reactive-data-and-queries).
Also I recommend to try the new updated driver and move to `collection`/`subscribe`/`publish` methods

**Comment by dr-dimitru** [comment] 2015-04-13 00:30
@alexfrieden  also I see what `sensitivities` array is empty everywhere, just found why - the name of node link should be wrapped into brackets, like: `MATCH (n) ...`

I'm not sure if it is bug on our end, cause neo4j call it "node pattern": [docs](http://neo4j.com/docs/2.2.0/cypher-comments.html)

**Comment by dr-dimitru** [comment] 2015-04-18 19:02
@alexfrieden Have you tried newer version to fit your needs and solve this issue?

**Comment by alexfrieden** [comment] 2015-04-21 00:49
Working on this now, going to uninstall and install new driver.  Does the new example use subscribe/publish?

**Comment by dr-dimitru** [comment] 2015-04-21 01:00
@alexfrieden yes, docs is redesigned with links to exact usage in [Meteor-Leaderboard-Neo4j](https://github.com/VeliovGroup/Meteor-Leaderboard-Neo4j) code. Also Meteor-Leaderboard-Neo4j is moved to `publish`/`subscribe` usage

**Comment by alexfrieden** [comment] 2015-04-21 01:13
So is subscribe now used in place of call?

**Comment by dr-dimitru** [comment] 2015-04-21 01:17
@alexfrieden Yes, and no.
I addition you can use returned data as miniMongo collection, search, sort and call other collection's methods - this is is main feature of it, and more close meteor-mongo syntax

**Comment by dr-dimitru** [comment] 2015-04-21 01:19
@alexfrieden also you can use `Meteor.neo4j.subscribe()` in `iron-router`'s `waitOn` function

**Comment by alexfrieden** [comment] 2015-04-21 01:24
So currently I am using call and it doesn't seem to be updating the same
client side document, should I be doing the mongo operations in order to do
that?

On Mon, Apr 20, 2015 at 9:19 PM, dr.dimitru <notifications@github.com>
wrote:

> @alexfrieden <https://github.com/alexfrieden> also you can use
> Meteor.neo4j.subscribe() in iron-router's waitOn function
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/VeliovGroup/ostrio-Neo4jreactivity/issues/30#issuecomment-94606048>
> .
>



-- 
Alexander Frieden

**Comment by dr-dimitru** [comment] 2015-04-21 01:25
@alexfrieden Nope, not to update. But your issue should be fixed in this case

**Comment by alexfrieden** [comment] 2015-04-21 01:27
Sorry a bit confused, so Meteor.neo4j.call('updateMethod' {params},
functionToDoStuff()) is not updating Neo4jCache document, so what is the
way to update it then?

On Mon, Apr 20, 2015 at 9:25 PM, dr.dimitru <notifications@github.com>
wrote:

> @alexfrieden <https://github.com/alexfrieden> Nope, not to update. But
> your issue should be fixed in this case
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/VeliovGroup/ostrio-Neo4jreactivity/issues/30#issuecomment-94606703>
> .
>



-- 
Alexander Frieden

**Comment by dr-dimitru** [comment] 2015-04-21 01:35
@alexfrieden `Meteor.neo4j.call()` isn't, it is updated in [neo4jdriver](https://github.com/VeliovGroup/ostrio-neo4jdriver) inside `listen` method, [here](https://github.com/VeliovGroup/ostrio-neo4jdriver/blob/master/ostrio:neo4jdriver.js#L97) and [here](https://github.com/VeliovGroup/ostrio-Neo4jreactivity/blob/master/ostrio:neo4jreactivity_driver.coffee#L495). 
To solve your case read this section: [About reactive data and queries](https://github.com/VeliovGroup/ostrio-Neo4jreactivity#about-reactive-data-and-queries)

**Comment by alexfrieden** [comment] 2015-04-21 02:00
Tried that, still is doing:
```
'updateBitPosition': function(){
		// console.log("position_x");
		// return 'MATCH n WHERE id(n)={_id} SET n.position_x = { position_x } RETURN';
		var cypherQuery = 'MATCH (a {uuid: {uuid}}) SET a.position_x = { position_x }';
		console.log(cypherQuery)
		return cypherQuery;
	}
```

and trying to call them by:
```
Meteor.neo4j.call('updateBitPosition',{
        uuid: neoId,
        position_x: x,
        position_y: y
      },function(error,data) {
        if (error)
        {
          console.log(error);
        }
        else
        {
          console.log("no error!  ")
          console.log(data);
        }
      });
```

**Comment by dr-dimitru** [comment] 2015-04-21 08:17
Every request is stored in cache collection unless you call it t twice

**Comment by dr-dimitru** [comment] 2015-04-21 08:25
At the same time as it stores you write request, it is updates all read requests which relay on updated data, on all clients - the reactivity

**Comment by dr-dimitru** [comment] 2015-04-27 00:44
@alexfrieden please update to latest version, probably your issue was caused by default Neo4j auth

**Comment by dr-dimitru** [comment] 2015-05-12 16:46
@alexfrieden any news on your end?

**Comment by lifeinchords** [comment] 2015-05-14 00:10
hey @dr-dimitru .. thanks for following up:
We got neo4j working via server side calls, without the reactivity part, I believe. Maybe our collaborator @Angel can describe the strategy more.. 

of what I understand, for now we're using Mongo as our primary data store, and neo for relational/graph data..
https://github.com/parallelsio/core-modules/blob/master/meteor-app/server/methods.js

Just started experimenting and will let you know how it goes
thanks
=: s

**Closed** 2015-05-14 10:16 UTC
Labels: question
